version: '3'
services:
    db:
        hostname: db
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password
        restart: always
#        volumes:
#            - ../data/mysql/data:/var/lib/mysql
#            - ../data/mysql/conf:/etc/mysql/conf.d
#            - ../data/mysql/initdb:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: starter
            MYSQL_ROOT_PASSWORD: root

    db_admin:
        image: adminer:latest
        restart: always
        ports:
            - 3006:8080
        depends_on:
            - db

    cache:
        hostname: cache
        image: redis:4
        command: redis-server --appendonly yes
        restart: always
#        volumes:
#            - ../data/redis:/data
        ports:
            - 6379:6379

    mq:
        hostname: mq
        image: webcenter/activemq:latest
        restart: always
        ports:
            - 61616:61616
            - 8161:8161

    elasticsearch:
        hostname: elasticsearch
        image: elasticsearch:latest
        restart: always
        ports:
            - 9200:9200
            - 9300:9300

    logstash:
        hostname: logstash
        image: registry.cn-shanghai.aliyuncs.com/hellodock/logstash:latest
        restart: always
        ports:
            - 9600:9600
            - 9601:9601
        depends_on:
            - elasticsearch

    kibana:
        image: registry.cn-shanghai.aliyuncs.com/hellodock/kibana:latest
        restart: always
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

    grafana:
        image: grafana/grafana:latest
        restart: always
        ports:
            - 3000:3000

    alertmanager:
        hostname: alertmanager
        image: registry.cn-shanghai.aliyuncs.com/hellodock/alertmanager:latest
        restart: always
        ports:
            - 9093:9093
        depends_on:
            - api

    prometheus:
        image: registry.cn-shanghai.aliyuncs.com/hellodock/prometheus:latest
        restart: always
        ports:
            - 9090:9090
        depends_on:
            - alertmanager
            - api

    api:
        hostname: api
        image: starter_api:latest
        build:
          context: .
          dockerfile: Dockerfile_ce
        restart: always
#        volumes:
#            - ../data/file:/tmp/file
        ports:
            - 8011:8011
        depends_on:
            - db
            - cache
            - mq
            - logstash

#    admin:
#        image: registry.cn-shanghai.aliyuncs.com/jext/starter_admin:latest
#        restart: always
#        ports:
#            - 8010:8010
#        depends_on:
#            - api
